-- begin ADPRO_DISTRICT
alter table ADPRO_DISTRICT add constraint FK_ADPRO_DISTRICT_ON_REGENCY foreign key (REGENCY_ID) references ADPRO_REGENCY(ID)^
create index IDX_ADPRO_DISTRICT_ON_REGENCY on ADPRO_DISTRICT (REGENCY_ID)^
create index IDX_ADPRO_DISTRICT on ADPRO_DISTRICT (REGENCY_ID, NAME)^
-- end ADPRO_DISTRICT
-- begin ADPRO_REGENCY
alter table ADPRO_REGENCY add constraint FK_ADPRO_REGENCY_ON_PROVINCE foreign key (PROVINCE_ID) references ADPRO_PROVINCE(ID)^
create index IDX_ADPRO_REGENCY_ON_PROVINCE on ADPRO_REGENCY (PROVINCE_ID)^
create index IDX_ADPRO_REGENCY on ADPRO_REGENCY (PROVINCE_ID, NAME)^
-- end ADPRO_REGENCY
-- begin ADPRO_PROVINCE
create index IDX_ADPRO_PROVINCE on ADPRO_PROVINCE (NAME)^
-- end ADPRO_PROVINCE
-- begin ADPRO_VILLAGE
alter table ADPRO_VILLAGE add constraint FK_ADPRO_VILLAGE_ON_DISTRICT foreign key (DISTRICT_ID) references ADPRO_DISTRICT(ID)^
create index IDX_ADPRO_VILLAGE_ON_DISTRICT on ADPRO_VILLAGE (DISTRICT_ID)^
create index IDX_ADPRO_VILLAGE on ADPRO_VILLAGE (DISTRICT_ID, NAME)^
-- end ADPRO_VILLAGE
