alter table ADPRO_VILLAGE add constraint FK_ADPRO_VILLAGE_ON_DISTRICT foreign key (DISTRICT_ID) references ADPRO_DISTRICT(ID);
create index IDX_ADPRO_VILLAGE_ON_DISTRICT on ADPRO_VILLAGE (DISTRICT_ID);
create index IDX_ADPRO_VILLAGE on ADPRO_VILLAGE (DISTRICT_ID, NAME);
