alter table ADPRO_REGENCY add constraint FK_ADPRO_REGENCY_ON_PROVINCE foreign key (PROVINCE_ID) references ADPRO_PROVINCE(ID);
create index IDX_ADPRO_REGENCY_ON_PROVINCE on ADPRO_REGENCY (PROVINCE_ID);
create index IDX_ADPRO_REGENCY on ADPRO_REGENCY (PROVINCE_ID, NAME);
