alter table ADPRO_INSTITUTION add constraint FK_ADPRO_INSTITUTION_ON_VILLAGE foreign key (VILLAGE_ID) references ADPRO_VILLAGE(ID);
create index IDX_ADPRO_INSTITUTION_ON_VILLAGE on ADPRO_INSTITUTION (VILLAGE_ID);
