alter table ADPRO_INSTITUTION add constraint FK_ADPRO_INSTITUTION_ON_DISTRICT foreign key (DISTRICT_ID) references ADPRO_DISTRICT(ID);
create index IDX_ADPRO_INSTITUTION_ON_DISTRICT on ADPRO_INSTITUTION (DISTRICT_ID);
