alter table ADPRO_INSTITUTION add constraint FK_ADPRO_INSTITUTION_ON_REGENCY foreign key (REGENCY_ID) references ADPRO_REGENCY(ID);
create index IDX_ADPRO_INSTITUTION_ON_REGENCY on ADPRO_INSTITUTION (REGENCY_ID);
